export const languageMap = {
  english: "English",
  hindi: "हिंदी",
  sanskrit: "संस्कृत",
  punjabi: "ਪੰਜਾਬੀ",
  marathi: "मराठी",
  gujarati: "ગુજરાતી",
  bengali: "বাংলা",
  tamil: "தமிழ்",
  telugu: "తెలుగు",
  kannada: "ಕನ್ನಡ",
  malayalam: "മലയാളം",
  kashmiri: "کشمیرى",
  urdu: "اردو",
  espanol: "Español",
  portuguese: "Português",
  italian: "Italiano",
  french: "Français",
  spanish: "Español",
  german: "Deutsch",
  japanese: "日本語",
  chinese: "中文",
  korean: "한국어",
  arabic: "العربية",
  indonesian: "Bahasa Indonesia",
  vietnamese: "Tiếng Việt",
  netherlands: "Nederlands",
  bhojpuri: "भोजपुरी",
  nepali: "नेपाली",
};

export const langTransMap = {
  english: {
    info: "A unique place to share knowledge and understand the world better.",
    salutation: ["Hello", "Welcome to Quora in English!"],
    description: (lang) =>
      `Add English to your languages on Quora. Your default language will remain, and you can easily switch between languages.`,
    add: "Add English",
    back: "Go back to English",
  },
  hindi: {
    info: "ज्ञान बाँटने और दुनिया को बेहतर ढंग से समझने की एक अनोखी जगह।",
    salutation: ["नमस्ते", "Quora हिन्दी में आपका स्वागत है!"],
    description: (lang) =>
      `Quora पर अपनी भाषाओं में हिन्दी जोड़ें। ${lang} आपकी डिफ़ॉल्ट भाषा बनी रहेगी और आप आसानी से भाषाएँ बदल सकते हैं।`,
    add: "हिन्दी जोड़ें",
    back: "हिन्दी पर वापस जाएँ",
  },
  sanskrit: {
    info: "ज्ञानं वितरितुं लोकं च सविशेषं ज्ञातुं स्थानं अद्वितीयम्।",
    salutation: ["नमः", "Quora संस्कृते स्वागतं!"],
    description: (lang) =>
      `Quora संस्कृतं भाषासु योजयतु। ${lang} तव डिफ़ॉल्ट् भाषा स्थास्यति, भाषाः चालयितुं सुगमं भविष्यति।`,
    add: "संस्कृतं योजयतु",
    back: "संस्कृतं प्रत्यागतं याहि।",
  },
  punjabi: {
    info: "ਗਿਆਨ ਸਾਂਝਾ ਕਰਨ ਅਤੇ ਦੁਨੀਆ ਨੂੰ ਵਧੀਆ ਸਮਝਣ ਲਈ ਇਕ ਵਿਲੱਖਣ ਜਗ੍ਹਾ।",
    salutation: ["ਸਤ ਸ੍ਰੀ ਅਕਾਲ", "Quora ਪੰਜਾਬੀ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ!"],
    description: (lang) =>
      `Quora 'ਤੇ ਆਪਣੇ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਪੰਜਾਬੀ ਸ਼ਾਮਲ ਕਰੋ। ਤੁਹਾਡੀ ਡਿਫਾਲਟ ਭਾਸ਼ਾ ਵਜੋਂ ${lang} ਰਹੇਗੀ ਅਤੇ ਤੁਸੀਂ ਆਸਾਨੀ ਨਾਲ ਭਾਸ਼ਾਵਾਂ ਬਦਲ ਸਕਦੇ ਹੋ।`,
    add: "ਪੰਜਾਬੀ ਸ਼ਾਮਲ ਕਰੋ",
    back: "ਪੰਜਾਬੀ ਤੇ ਵਾਪਸ ਜਾਓ।",
  },
  marathi: {
    info: "ज्ञान सामायिक करण्यासाठी आणि जग अधिक चांगल्या प्रकारे समजण्यासाठी एक अनोखी जागा।",
    salutation: ["नमस्कार", "Quora मराठीमध्ये आपले स्वागत आहे!"],
    description: (lang) =>
      `Quora वर आपल्या भाषांमध्ये मराठी जोडा. आपली डीफॉल्ट भाषा ${lang} राहील आणि आपण सहजपणे भाषा बदलू शकता.`,
    add: "मराठी जोडा",
    back: "मराठीवर परत जा",
  },
  gujarati: {
    info: "જ્ઞાન વહેંચવા અને દુનિયાને સારી રીતે સમજવા માટે એક અનોખું સ્થળ।",
    salutation: ["નમસ્તે", "Quora ગુજરાતી માં તમારું સ્વાગત છે!"],
    description: (lang) =>
      `Quora પર તમારી ભાષાઓમાં ગુજરાતી ઉમેરો. તમારું ડિફોલ્ટ ભાષા ${lang} રહેશે અને તમે સરળતાથી ભાષાઓ બદલશો.`,
    add: "ગુજરાતી ઉમેરો",
    back: "ગુજરાતી પર પાછા ફરો",
  },
  bengali: {
    info: "জ্ঞান ভাগ করে নেওয়ার এবং বিশ্বকে আরও ভালভাবে বোঝার একটি অনন্য জায়গা।",
    salutation: ["নমস্কার", "Quora বাংলায় আপনাকে স্বাগত জানাই!"],
    description: (lang) =>
      `Quora-তে আপনার ভাষাগুলিতে বাংলা যোগ করুন। ${lang} আপনার ডিফল্ট ভাষা থাকবে এবং আপনি সহজেই ভাষা পরিবর্তন করতে পারবেন।`,
    add: "বাংলা যোগ করুন",
    back: "বাংলায় ফিরে যান",
  },
  tamil: {
    info: "அறிவைப் பகிர்ந்து கொள்ளவும், உலகத்தைச் சிறப்பாக புரிந்துகொள்ளவும் ஒரு தனிப்பட்ட இடம்.",
    salutation: ["வணக்கம்", "Quora தமிழில் உங்களை வரவேற்கிறது!"],
    description: (lang) =>
      `Quora இல் உங்கள் மொழிகளில் தமிழ் சேர்க்கவும். உங்கள் இயல்புநிலை மொழியாக ${lang} இருக்கும், மேலும் நீங்கள் மொழிகளை எளிதாக மாற்றலாம்.`,
    add: "தமிழ் சேர்க்கவும்",
    back: "தமிழுக்கு திரும்பவும்",
  },
  telugu: {
    info: "జ్ఞానాన్ని పంచుకోవడానికి మరియు ప్రపంచాన్ని బాగా అర్థం చేసుకోవడానికి ప్రత్యేకమైన ప్రదేశం.",
    salutation: ["నమస్తే", "Quora తెలుగులోకి స్వాగతం!"],
    description: (lang) =>
      `Quora లో మీ భాషలలో తెలుగు చేర్చండి. మీ డిఫాల్ట్ భాష ${lang}గా ఉంటుంది మరియు మీరు భాషలను సులభంగా మార్చవచ్చు.",
    add: "తెలుగు చేర్చండి",
    back: "తెలుగుకు తిరిగి వెళ్ళండి`,
  },
  kannada: {
    info: "ಜ್ಞಾನವನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಮತ್ತು ಲೋಕವನ್ನು ಉತ್ತಮವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ವಿಶಿಷ್ಟವಾದ ಸ್ಥಳ.",
    salutation: ["ನಮಸ್ಕಾರ", "Quora ಕನ್ನಡಕ್ಕೆ ಸ್ವಾಗತ!"],
    description: (lang) =>
      `Quora ನಲ್ಲಿ ನಿಮ್ಮ ಭಾಷೆಗಳಲ್ಲಿ ಕನ್ನಡವನ್ನು ಸೇರಿಸಿ. ನಿಮ್ಮ ಡೀಫಾಲ್ಟ್ ಭಾಷೆ ${lang} ಆಗಿರುತ್ತದೆ ಮತ್ತು ನೀವು ಸುಲಭವಾಗಿ ಭಾಷೆಗಳನ್ನು ಬದಲಾಯಿಸಬಹುದು.`,
    add: "ಕನ್ನಡವನ್ನು ಸೇರಿಸಿ",
    back: "ಕನ್ನಡಕ್ಕೆ ಹಿಂತಿರುಗಿ",
  },
  malayalam: {
    info: "വിജ്ഞാനം പങ്കിടാനും ലോകത്തെ മികച്ച രീതിയിൽ മനസിലാക്കാനും ഒരു പ്രത്യേകമായ സ്ഥലം.",
    salutation: ["വണക്കം", "Quora മലയാളത്തിൽ സ്വാഗതം!"],
    description: (lang) =>
      `Quora-യിൽ നിങ്ങളുടെ ഭാഷകളിൽ മലയാളം ചേർക്കുക. നിങ്ങളുടെ ഡീഫാൾട്ട് ഭാഷ ${lang} ആയിരിക്കും, നിങ്ങൾ എളുപ്പത്തിൽ ഭാഷകൾ മാറാൻ കഴിയും.`,

    add: "മലയാളം ചേർക്കുക",
    back: "മലയാളത്തിലേക്ക് മടങ്ങുക",
  },
  kashmiri: {
    info: "اِک انوکھا مقام جہاں علم بانٹنے اور دنیا کو بہتر سمجھنے کا موقع ملے۔",
    salutation: ["السلام علیکم", "Quora کشمیری میں خوش آمدید!"],
    description: (lang) =>
      `Quora پر اپنی زبانوں میں کشمیری شامل کریں۔ آپ کی ڈیفالٹ زبان ${lang} رہے گی اور آپ آسانی سے زبانیں تبدیل کر سکتے ہیں۔`,
    add: "کشمیری شامل کریں",
    back: "کشمیری پر واپس جائیں",
  },
  urdu: {
    info: "ایک منفرد جگہ جہاں علم بانٹنے اور دنیا کو بہتر سمجھنے کا موقع ملتا ہے۔",
    salutation: ["السلام علیکم", "Quora اردو میں خوش آمدید!"],
    description: (lang) =>
      `Quora پر اپنی زبانوں میں اردو شامل کریں۔ آپ کی ڈیفالٹ زبان ${lang} رہے گی اور آپ آسانی سے زبانیں تبدیل کر سکتے ہیں۔`,
    add: "اردو شامل کریں",
    back: "اردو پر واپس جائیں",
  },
  espanol: {
    info: "Un lugar único para compartir conocimientos y comprender mejor el mundo.",
    salutation: ["Hola", "¡Bienvenido a Quora en Español!"],
    description: (lang) =>
      `Agregue Español a sus idiomas en Quora. Su idioma predeterminado seguirá siendo el ${lang} y podrá cambiar entre idiomas fácilmente.`,
    add: "Agregar Español",
    back: "Volver a Español",
  },
  portuguese: {
    info: "Um lugar único para compartilhar conhecimento e entender melhor o mundo.",
    salutation: ["Olá", "Bem-vindo ao Quora em Português!"],
    description: (lang) =>
      `Adicione Português aos seus idiomas no Quora. Seu idioma padrão continuará sendo o ${lang}, e você poderá alternar entre idiomas facilmente.`,
    add: "Adicionar Português",
    back: "Voltar ao Português",
  },
  italian: {
    info: "Un luogo unico per condividere conoscenze e comprendere meglio il mondo.",
    salutation: ["Ciao", "Benvenuto su Quora in Italiano!"],
    description: (lang) =>
      `Aggiungi Italiano alle tue lingue su Quora. La tua lingua predefinita rimarrà l'${lang} e potrai passare facilmente da una lingua all'altra.`,
    add: "Aggiungi Italiano",
    back: "Torna all'Italiano",
  },
  french: {
    info: "Un endroit unique pour partager des connaissances et mieux comprendre le monde.",
    salutation: ["Bonjour", "Bienvenue sur Quora en Français!"],
    description: (lang) =>
      `Ajoutez Français à vos langues sur Quora. Votre langue par défaut restera l'${lang} et vous pourrez facilement changer de langue.`,
    add: "Ajouter Français",
    back: "Retourner au Français",
  },
  spanish: {
    info: "Un lugar único para compartir conocimientos y comprender mejor el mundo.",
    salutation: ["Hola", "¡Bienvenido a Quora en Español!"],
    description: (lang) =>
      `Agregue Español a sus idiomas en Quora. Su idioma predeterminado seguirá siendo el ${lang} y podrá cambiar entre idiomas fácilmente.`,
    add: "Agregar Español",
    back: "Volver a Español",
  },
  german: {
    info: "Ein einzigartiger Ort, um Wissen zu teilen und die Welt besser zu verstehen.",
    salutation: ["Hallo", "Willkommen bei Quora auf Deutsch!"],
    description: (lang) =>
      `Fügen Sie Deutsch zu Ihren Sprachen auf Quora hinzu. Ihre Standardsprache bleibt ${lang}, und Sie können problemlos zwischen den Sprachen wechseln.`,
    add: "Deutsch hinzufügen",
    back: "Zurück zu Deutsch",
  },
  japanese: {
    info: "知識を共有し、世界をよりよく理解するためのユニークな場所。",
    salutation: ["こんにちは", "Quoraへようこそ！"],
    description: (lang) =>
      `Quoraの言語に日本語を追加しましょう。デフォルトの言語は${lang}のままで、簡単に言語を切り替えることができます。`,
    add: "日本語を追加する",
    back: "日本語に戻る",
  },
  chinese: {
    info: "一个分享知识并更好地理解世界的独特地方。",
    salutation: ["你好", "欢迎来到中文的Quora！"],
    description: (lang) =>
      `在Quora中添加中文。您的默认语言将保持为${lang}，并且您可以轻松切换语言。`,
    add: "添加中文",
    back: "返回中文",
  },
  korean: {
    info: "지식을 공유하고 세상을 더 잘 이해할 수 있는 독특한 장소.",
    salutation: ["안녕하세요", "Quora 한국어에 오신 것을 환영합니다!"],
    description: (lang) =>
      `Quora에서 한국어를 추가하세요. 기본 언어는 ${lang}로 유지되며 쉽게 언어를 전환할 수 있습니다.`,
    add: "한국어 추가",
    back: "한국어로 돌아가기",
  },
  arabic: {
    info: "مكان فريد لمشاركة المعرفة وفهم العالم بشكل أفضل.",
    salutation: ["مرحبًا", "مرحبًا بك في Quora بالعربية!"],
    description: (lang) =>
      `أضف العربية إلى لغاتك على Quora. ستظل لغتك الافتراضية هي ${lang} ويمكنك التبديل بين اللغات بسهولة.`,
    add: "أضف العربية",
    back: "العودة إلى العربية",
  },
  indonesian: {
    info: "Tempat unik untuk berbagi pengetahuan dan memahami dunia dengan lebih baik.",
    salutation: ["Halo", "Selamat datang di Quora dalam Bahasa Indonesia!"],
    description: (lang) =>
      `Tambahkan Bahasa Indonesia ke dalam bahasa Anda di Quora. Bahasa default Anda akan tetap bahasa ${lang}, dan Anda dapat dengan mudah beralih antara bahasa.`,
    add: "Tambahkan Bahasa Indonesia",
    back: "Kembali ke Bahasa Indonesia",
  },
  vietnamese: {
    info: "Một nơi độc đáo để chia sẻ kiến thức và hiểu thế giới tốt hơn.",
    salutation: ["Xin chào", "Chào mừng bạn đến với Quora bằng Tiếng Việt!"],
    description: (lang) =>
      `Thêm Tiếng Việt vào ngôn ngữ của bạn trên Quora. Ngôn ngữ mặc định của bạn sẽ vẫn là ${lang}, và bạn có thể dễ dàng chuyển đổi giữa các ngôn ngữ.`,
    add: "Thêm Tiếng Việt",
    back: "Quay lại Tiếng Việt",
  },
  netherlands: {
    info: "Een unieke plek om kennis te delen en de wereld beter te begrijpen.",
    salutation: ["Hallo", "Welkom bij Quora in het Nederlands!"],
    description: (lang) =>
      `Voeg Nederlands toe aan je talen op Quora. Je standaardtaal blijft ${lang}, en je kunt gemakkelijk tussen talen schakelen.`,
    add: "Voeg Nederlands toe",
    back: "Ga terug naar Nederlands",
  },
  bhojpuri: {
    info: "ज्ञान बाँटे आ दुनिया के बढ़िया से समझे के एक अनोखा जगह।",
    salutation: ["नमस्ते", "Quora भोजपुरी में राउर स्वागत बा!"],
    description: (lang) =>
      `Quora पर अपने भाषा में भोजपुरी जोड़ल जाव। राउर डिफ़ॉल्ट भाषा ${lang} रही, आ राउर आसानी से भाषा बदले के सुविधा रही।`,
    add: "भोजपुरी जोड़ल जाव",
    back: "भोजपुरी पर वापिस जाईं",
  },
  nepali: {
    info: "ज्ञान बाँड्ने र संसारलाई राम्रोसँग बुझ्नको लागि एक अनौठो स्थान।",
    salutation: ["नमस्ते", "Quora नेपालीमा तपाईँलाई स्वागत छ!"],
    description: (lang) =>
      `Quora मा आफ्नो भाषाहरूमा नेपाली थप्नुहोस्। तपाईँको डिफल्ट भाषा ${lang} रहनेछ र तपाईँ सजिलै भाषाहरू परिवर्तन गर्न सक्नुहुनेछ।`,
    add: "नेपाली थप्नुहोस्",
    back: "नेपालीमा फर्कनुहोस्",
  },
};

export const languageNamesMap = {
  english: {
    hindi: "अंग्रेज़ी",
    sanskrit: "आंग्ल भाषा",
    punjabi: "ਅੰਗਰੇਜ਼ੀ",
    marathi: "इंग्रजी",
    gujarati: "અંગ્રેજી",
    bengali: "ইংরেজি",
    tamil: "ஆங்கிலம்",
    telugu: "ఆంగ్లం",
    kannada: "ಇಂಗ್ಲಿಷ್",
    malayalam: "ഇംഗ്ലീഷ്",
    kashmiri: "اَنگریٖزی",
    urdu: "انگریزی",
    espanol: "Inglés",
    portuguese: "Inglês",
    italian: "Inglese",
    french: "Anglais",
    spanish: "Inglés",
    german: "Englisch",
    japanese: "英語",
    chinese: "英语",
    korean: "영어",
    arabic: "الإنجليزية",
    indonesian: "Inggris",
    vietnamese: "Tiếng Anh",
    netherlands: "Engels",
    bhojpuri: "अंगरेजी",
    nepali: "अङ्ग्रेजी",
  },
  hindi: {
    english: "Hindi",
    sanskrit: "हिन्दी",
    punjabi: "ਹਿੰਦੀ",
    marathi: "हिंदी",
    gujarati: "હિન્દી",
    bengali: "হিন্দি",
    tamil: "ஹிந்தி",
    telugu: "హిందీ",
    kannada: "ಹಿಂದು",
    malayalam: "ഹിന്ദി",
    kashmiri: "ہٖندٖستٕ",
    urdu: "ہندی",
    espanol: "Hindí",
    portuguese: "Hindi",
    italian: "Hindi",
    french: "Hindi",
    spanish: "Hindí",
    german: "Hindi",
    japanese: "ヒンディー語",
    chinese: "印地语",
    korean: "힌디어",
    arabic: "الهندية",
    indonesian: "Hindi",
    vietnamese: "Tiếng Hindi",
    netherlands: "Hindi",
    bhojpuri: "हिंदी",
    nepali: "हिन्दी",
  },
  sanskrit: {
    english: "Sanskrit",
    hindi: "संस्कृत",
    punjabi: "ਸੰਸਕ੍ਰਿਤ",
    marathi: "संस्कृत",
    gujarati: "સંસ્કૃત",
    bengali: "সংস্কৃত",
    tamil: "சமஸ்கிருதம்",
    telugu: "సంస్కృతం",
    kannada: "ಸಂಸ್ಕೃತ",
    malayalam: "സംസ്കൃതം",
    kashmiri: "سَنسکٕرٕت",
    urdu: "سنسکرت",
    espanol: "Sánscrito",
    portuguese: "Sânscrito",
    italian: "Sanscrito",
    french: "Sanskrit",
    spanish: "Sánscrito",
    german: "Sanskrit",
    japanese: "サンスクリット語",
    chinese: "梵语",
    korean: "산스크리트어",
    arabic: "السنسكريتية",
    indonesian: "Sanskerta",
    vietnamese: "Tiếng Phạn",
    netherlands: "Sanskriet",
    bhojpuri: "संस्कृत",
    nepali: "संस्कृत",
  },
  punjabi: {
    english: "Punjabi",
    hindi: "पंजाबी",
    sanskrit: "पञ्जाबी",
    marathi: "पंजाबी",
    gujarati: "પંજાબી",
    bengali: "পাঞ্জাবি",
    tamil: "பஞ்சாபி",
    telugu: "పంజాబీ",
    kannada: "ಪಂಜಾಬಿ",
    malayalam: "പഞ്ചാബി",
    kashmiri: "پَنجابی",
    urdu: "پنجابی",
    espanol: "Panyabí",
    portuguese: "Punjabi",
    italian: "Punjabi",
    french: "Punjabi",
    spanish: "Panyabí",
    german: "Punjabi",
    japanese: "パンジャブ語",
    chinese: "旁遮普语",
    korean: "펀자브어",
    arabic: "البنجابية",
    indonesian: "Punjabi",
    vietnamese: "Tiếng Punjab",
    netherlands: "Punjabi",
    bhojpuri: "पंजाबी",
    nepali: "पञ्जाबी",
  },
  marathi: {
    english: "Marathi",
    hindi: "मराठी",
    sanskrit: "मराठी",
    punjabi: "ਮਰਾਠੀ",
    gujarati: "મરાઠી",
    bengali: "মারাঠি",
    tamil: "மராத்தி",
    telugu: "మరాఠీ",
    kannada: "ಮರಾಠಿ",
    malayalam: "മറാത്തി",
    kashmiri: "مَرٛاٹھی",
    urdu: "مراٹھی",
    espanol: "Maratí",
    portuguese: "Marati",
    italian: "Marathi",
    french: "Marathi",
    spanish: "Maratí",
    german: "Marathi",
    japanese: "マラーティー語",
    chinese: "马拉地语",
    korean: "마라티어",
    arabic: "الماراثية",
    indonesian: "Marathi",
    vietnamese: "Tiếng Marathi",
    netherlands: "Marathi",
    bhojpuri: "मराठी",
    nepali: "मराठी",
  },
  gujarati: {
    english: "Gujarati",
    hindi: "गुजराती",
    bengali: "গুজরাটি",
    tamil: "குஜராத்தி",
    telugu: "గుజరాతీ",
    kannada: "ಗುಜರಾತಿ",
    malayalam: "ഗുജറാത്തി",
    kashmiri: "گُجَراتی",
    urdu: "گجراتی",
    espanol: "Gujarati",
    portuguese: "Gujarati",
    italian: "Gujarati",
    french: "Gujarati",
    spanish: "Gujarati",
    german: "Gujarati",
    japanese: "グジャラート語",
    chinese: "古吉拉特语",
    korean: "구자라티어",
    arabic: "الغوجاراتية",
    indonesian: "Gujarati",
    vietnamese: "Tiếng Gujarati",
    netherlands: "Gujarati",
    bhojpuri: "गुजराती",
    nepali: "गुजराती",
  },
  bengali: {
    english: "Bengali",
    hindi: "बंगाली",
    gujarati: "બંગાળી",
    tamil: "பெங்காலி",
    telugu: "బెంగాలీ",
    kannada: "ಬೆಂಗಾಲಿ",
    malayalam: "ബംഗാളി",
    kashmiri: "بنگالی",
    urdu: "بنگالی",
    espanol: "Bengalí",
    portuguese: "Bengali",
    italian: "Bengalese",
    french: "Bengali",
    spanish: "Bengalí",
    german: "Bengalisch",
    japanese: "ベンガル語",
    chinese: "孟加拉语",
    korean: "벵골어",
    arabic: "البنغالية",
    indonesian: "Bengali",
    vietnamese: "Tiếng Bengal",
    netherlands: "Bengaals",
    bhojpuri: "बंगाली",
    nepali: "बंगाली",
  },
  tamil: {
    english: "Tamil",
    hindi: "तमिल",
    gujarati: "તમિલ",
    bengali: "তামিল",
    telugu: "తమిళం",
    kannada: "ತಮಿಳು",
    malayalam: "തമിഴ്",
    kashmiri: "تَمل",
    urdu: "تمل",
    espanol: "Tamil",
    portuguese: "Tâmil",
    italian: "Tamil",
    french: "Tamoul",
    spanish: "Tamil",
    german: "Tamil",
    japanese: "タミル語",
    chinese: "泰米尔语",
    korean: "타밀어",
    arabic: "التاميلية",
    indonesian: "Tamil",
    vietnamese: "Tiếng Tamil",
    netherlands: "Tamil",
    bhojpuri: "तमिल",
    nepali: "तमिल",
  },
  telugu: {
    english: "Telugu",
    hindi: "तेलुगु",
    gujarati: "તેલુગુ",
    bengali: "তেলেগু",
    tamil: "தெலுங்கு",
    kannada: "ತೆಲುಗು",
    malayalam: "തെലുങ്കു",
    kashmiri: "تٕلٕگوٗ",
    urdu: "تلگو",
    espanol: "Telugu",
    portuguese: "Telugu",
    italian: "Telugu",
    french: "Télougou",
    spanish: "Telugu",
    german: "Telugu",
    japanese: "テルグ語",
    chinese: "泰卢固语",
    korean: "텔루구어",
    arabic: "التيلجو",
    indonesian: "Telugu",
    vietnamese: "Tiếng Telugu",
    netherlands: "Telugu",
    bhojpuri: "तेलुगु",
    nepali: "तेलुगु",
  },
  kannada: {
    english: "Kannada",
    hindi: "कन्नड़",
    gujarati: "કન્નડ",
    bengali: "কন্নড়",
    tamil: "கன்னடம்",
    telugu: "కన్నడ",
    malayalam: "കന്നഡ",
    kashmiri: "کَنٛنٛڑ",
    urdu: "کنڑ",
    espanol: "Kannada",
    portuguese: "Kannada",
    italian: "Kannada",
    french: "Kannada",
    spanish: "Kannada",
    german: "Kannada",
    japanese: "カンナダ語",
    chinese: "卡纳达语",
    korean: "칸나다어",
    arabic: "الكانادا",
    indonesian: "Kannada",
    vietnamese: "Tiếng Kannada",
    netherlands: "Kannada",
    bhojpuri: "कन्नड़",
    nepali: "कन्नड",
  },
  malayalam: {
    english: "Malayalam",
    hindi: "मलयालम",
    gujarati: "મલયાલમ",
    bengali: "মালয়ালম",
    tamil: "மலையாளம்",
    telugu: "మలయాళం",
    kannada: "ಮಲಯಾಳಂ",
    kashmiri: "مَلایَالم",
    urdu: "ملیالم",
    espanol: "Malayalam",
    portuguese: "Malayalam",
    italian: "Malayalam",
    french: "Malayâlam",
    spanish: "Malayalam",
    german: "Malayalam",
    japanese: "マラヤーラム語",
    chinese: "马拉雅拉姆语",
    korean: "말라얄람어",
    arabic: "المالايالامية",
    indonesian: "Malayalam",
    vietnamese: "Tiếng Malayalam",
    netherlands: "Malayalam",
    bhojpuri: "मलयालम",
    nepali: "मलयालम",
  },
  kashmiri: {
    english: "Kashmiri",
    hindi: "कश्मीरी",
    gujarati: "કશ્મીરી",
    bengali: "কাশ্মীরি",
    tamil: "காஷ்மிரி",
    telugu: "కాశ్మీరీ",
    kannada: "ಕಾಶ್ಮೀರಿ",
    malayalam: "കാശ്മീരി",
    kashmiri: "کٲشُر",
    urdu: "کشمیری",
    espanol: "Cachemiro",
    portuguese: "Caxemira",
    italian: "Kashmiro",
    french: "Cachemiri",
    spanish: "Cachemiro",
    german: "Kaschmirisch",
    japanese: "カシミール語",
    chinese: "克什米尔语",
    korean: "카슈미르어",
    arabic: "الكشميرية",
    indonesian: "Kashmiri",
    vietnamese: "Tiếng Kashmir",
    netherlands: "Kasjmir",
    bhojpuri: "कश्मीरी",
    nepali: "कश्मीरी",
  },
  urdu: {
    english: "Urdu",
    hindi: "उर्दू",
    gujarati: "ઉર્દૂ",
    bengali: "উর্দু",
    tamil: "உருது",
    telugu: "ఉర్దూ",
    kannada: "ಉರ್ದು",
    malayalam: "ഉർദു",
    kashmiri: "اُردوٗ",
    urdu: "اردو",
    espanol: "Urdu",
    portuguese: "Urdu",
    italian: "Urdu",
    french: "Ourdou",
    spanish: "Urdu",
    german: "Urdu",
    japanese: "ウルドゥー語",
    chinese: "乌尔都语",
    korean: "우르두어",
    arabic: "الأردية",
    indonesian: "Urdu",
    vietnamese: "Tiếng Urdu",
    netherlands: "Urdu",
    bhojpuri: "उर्दू",
    nepali: "उर्दू",
  },
  espanol: {
    english: "Spanish",
    hindi: "स्पैनिश",
    gujarati: "સ્પેનિશ",
    bengali: "স্প্যানিশ",
    tamil: "ஸ்பானிஷ்",
    telugu: "స్పానిష్",
    kannada: "ಸ್ಪಾನಿಷ್",
    malayalam: "സ്പാനിഷ്",
    kashmiri: "سپینٛش",
    urdu: "ہسپانوی",
    espanol: "Español",
    portuguese: "Espanhol",
    italian: "Spagnolo",
    french: "Espagnol",
    spanish: "Español",
    german: "Spanisch",
    japanese: "スペイン語",
    chinese: "西班牙语",
    korean: "스페인어",
    arabic: "الإسبانية",
    indonesian: "Spanyol",
    vietnamese: "Tiếng Tây Ban Nha",
    netherlands: "Spaans",
    bhojpuri: "स्पैनिश",
    nepali: "स्पेनिश",
  },
  portuguese: {
    english: "Portuguese",
    hindi: "पुर्तगाली",
    gujarati: "પોર્ટુગીઝ",
    bengali: "পর্তুগিজ",
    tamil: "போர்டுகீஸ்",
    telugu: "పోర్చుగీసు",
    kannada: "ಪೋರ್ಚುಗೀಸ್",
    malayalam: "പോർച്ചുഗീസ്",
    kashmiri: "پورتٕگیٖز",
    urdu: "پرتگالی",
    espanol: "Portugués",
    portuguese: "Português",
    italian: "Portoghese",
    french: "Portugais",
    spanish: "Portugués",
    german: "Portugiesisch",
    japanese: "ポルトガル語",
    chinese: "葡萄牙语",
    korean: "포르투갈어",
    arabic: "البرتغالية",
    indonesian: "Portugis",
    vietnamese: "Tiếng Bồ Đào Nha",
    netherlands: "Portugees",
    bhojpuri: "पुर्तगाली",
    nepali: "पुर्तगाली",
  },
  italian: {
    english: "Italian",
    hindi: "इटालियन",
    gujarati: "ઇટાલિયન",
    bengali: "ইতালীয়",
    tamil: "இத்தாலியன்",
    telugu: "ఇటాలియన్",
    kannada: "ಇಟಾಲಿಯನ್",
    malayalam: "ഇറ്റാലിയൻ",
    kashmiri: "اِٹالِیَن",
    urdu: "اطالوی",
    espanol: "Italiano",
    portuguese: "Italiano",
    italian: "Italiano",
    french: "Italien",
    spanish: "Italiano",
    german: "Italienisch",
    japanese: "イタリア語",
    chinese: "意大利语",
    korean: "이탈리아어",
    arabic: "الإيطالية",
    indonesian: "Italia",
    vietnamese: "Tiếng Ý",
    netherlands: "Italiaans",
    bhojpuri: "इटालियन",
    nepali: "इटालियन",
  },
  french: {
    english: "French",
    hindi: "फ्रेंच",
    gujarati: "ફ્રેંચ",
    bengali: "ফরাসি",
    tamil: "பிரெஞ்சு",
    telugu: "ఫ్రెంచ్",
    kannada: "ಫ್ರೆಂಚ್",
    malayalam: "ഫ്രഞ്ച്",
    kashmiri: "فِرٛنچ",
    urdu: "فرانسیسی",
    espanol: "Francés",
    portuguese: "Francês",
    italian: "Francese",
    french: "Français",
    spanish: "Francés",
    german: "Französisch",
    japanese: "フランス語",
    chinese: "法语",
    korean: "프랑스어",
    arabic: "الفرنسية",
    indonesian: "Perancis",
    vietnamese: "Tiếng Pháp",
    netherlands: "Frans",
    bhojpuri: "फ्रेंच",
    nepali: "फ्रेंच",
  },
  spanish: {
    english: "Spanish",
    hindi: "स्पैनिश",
    gujarati: "સ્પેનિશ",
    bengali: "স্প্যানিশ",
    tamil: "ஸ்பானிஷ்",
    telugu: "స్పానిష్",
    kannada: "ಸ್ಪಾನಿಷ್",
    malayalam: "സ്പാനിഷ്",
    kashmiri: "سپینٛش",
    urdu: "ہسپانوی",
    espanol: "Español",
    portuguese: "Espanhol",
    italian: "Spagnolo",
    french: "Espagnol",
    spanish: "Español",
    german: "Spanisch",
    japanese: "スペイン語",
    chinese: "西班牙语",
    korean: "스페인어",
    arabic: "الإسبانية",
    indonesian: "Spanyol",
    vietnamese: "Tiếng Tây Ban Nha",
    netherlands: "Spaans",
    bhojpuri: "स्पैनिश",
    nepali: "स्पेनिश",
  },
  german: {
    english: "German",
    hindi: "जर्मन",
    gujarati: "જર્મન",
    bengali: "জার্মান",
    tamil: "ஜெர்மன்",
    telugu: "జర్మన్",
    kannada: "ಜರ್ಮನ್",
    malayalam: "ജർമ്മൻ",
    kashmiri: "جرٛمن",
    urdu: "جرمن",
    espanol: "Alemán",
    portuguese: "Alemão",
    italian: "Tedesco",
    french: "Allemand",
    spanish: "Alemán",
    german: "Deutsch",
    japanese: "ドイツ語",
    chinese: "德语",
    korean: "독일어",
    arabic: "الألمانية",
    indonesian: "Jerman",
    vietnamese: "Tiếng Đức",
    netherlands: "Duits",
    bhojpuri: "जर्मन",
    nepali: "जर्मन",
  },
  japanese: {
    english: "Japanese",
    hindi: "जापानी",
    gujarati: "જાપાનીઝ",
    bengali: "জাপানি",
    tamil: "ஜப்பானியம்",
    telugu: "జపనీస్",
    kannada: "ಜಾಪಾನೀಸ್",
    malayalam: "ജാപ്പനീസ്",
    kashmiri: "جاپٕنیٖز",
    urdu: "جاپانی",
    espanol: "Japonés",
    portuguese: "Japonês",
    italian: "Giapponese",
    french: "Japonais",
    spanish: "Japonés",
    german: "Japanisch",
    japanese: "日本語",
    chinese: "日语",
    korean: "일본어",
    arabic: "اليابانية",
    indonesian: "Jepang",
    vietnamese: "Tiếng Nhật",
    netherlands: "Japans",
    bhojpuri: "जापानी",
    nepali: "जापानी",
  },
  chinese: {
    english: "Chinese",
    hindi: "चीनी",
    gujarati: "ચાઇનીઝ",
    bengali: "চীনা",
    tamil: "சீனம்",
    telugu: "చైనా",
    kannada: "ಚೈನೀಸ್",
    malayalam: "ചൈനീസ്",
    kashmiri: "چیٖنٛیٖز",
    urdu: "چینی",
    espanol: "Chino",
    portuguese: "Chinês",
    italian: "Cinese",
    french: "Chinois",
    spanish: "Chino",
    german: "Chinesisch",
    japanese: "中国語",
    chinese: "中文",
    korean: "중국어",
    arabic: "الصينية",
    indonesian: "Cina",
    vietnamese: "Tiếng Trung",
    netherlands: "Chinees",
    bhojpuri: "चीनी",
    nepali: "चिनी",
  },
  korean: {
    english: "Korean",
    hindi: "कोरियाई",
    gujarati: "કોરિયન",
    bengali: "কোরিয়ান",
    tamil: "கொரியன்",
    telugu: "కోరియన్",
    kannada: "ಕೊರಿಯನ್",
    malayalam: "കൊറിയൻ",
    kashmiri: "کورٛیَن",
    urdu: "کوریائی",
    espanol: "Coreano",
    portuguese: "Coreano",
    italian: "Coreano",
    french: "Coréen",
    spanish: "Coreano",
    german: "Koreanisch",
    japanese: "韓国語",
    chinese: "韩语",
    korean: "한국어",
    arabic: "الكورية",
    indonesian: "Korea",
    vietnamese: "Tiếng Hàn",
    netherlands: "Koreaans",
    bhojpuri: "कोरियन",
    nepali: "कोरियन",
  },
  arabic: {
    english: "Arabic",
    hindi: "अरबी",
    gujarati: "અરેબિક",
    bengali: "আরবি",
    tamil: "அரபு",
    telugu: "అరబిక్",
    kannada: "ಅರೇಬಿಕ್",
    malayalam: "അറബിക്",
    kashmiri: "عربی",
    urdu: "عربی",
    espanol: "Árabe",
    portuguese: "Árabe",
    italian: "Arabo",
    french: "Arabe",
    spanish: "Árabe",
    german: "Arabisch",
    japanese: "アラビア語",
    chinese: "阿拉伯语",
    korean: "아랍어",
    arabic: "العربية",
    indonesian: "Arab",
    vietnamese: "Tiếng Ả Rập",
    netherlands: "Arabisch",
    bhojpuri: "अरबी",
    nepali: "अरबी",
  },
  indonesian: {
    english: "Indonesian",
    hindi: "इंडोनेशियाई",
    gujarati: "ઇન્ડોનેશિયન",
    bengali: "ইন্দোনেশীয়",
    tamil: "இந்தோனேஷியன்",
    telugu: "ఇండోనేషియన్",
    kannada: "ಇಂಡೋನೇಷಿಯನ್",
    malayalam: "ഇൻഡോനേഷ്യൻ",
    kashmiri: "اِنڈونیشِیَن",
    urdu: "انڈونیشی",
    espanol: "Indonesio",
    portuguese: "Indonésio",
    italian: "Indonesiano",
    french: "Indonésien",
    spanish: "Indonesio",
    german: "Indonesisch",
    japanese: "インドネシア語",
    chinese: "印度尼西亚语",
    korean: "인도네시아어",
    arabic: "الإندونيسية",
    indonesian: "Bahasa Indonesia",
    vietnamese: "Tiếng Indonesia",
    netherlands: "Indonesisch",
    bhojpuri: "इंडोनेशियाई",
    nepali: "इन्डोनेसियन",
  },
  vietnamese: {
    english: "Vietnamese",
    hindi: "वियतनामी",
    gujarati: "વિયેતનામી",
    bengali: "ভিয়েতনামী",
    tamil: "வியட்நாமீஸ்",
    telugu: "వియత్నామీస్",
    kannada: "ವಿಯೆಟ್ನಾಮೀಸ್",
    malayalam: "വിയറ്റ്നാമീസ്",
    kashmiri: "وِیَٹنامِیٖز",
    urdu: "ویتنامی",
    espanol: "Vietnamita",
    portuguese: "Vietnamita",
    italian: "Vietnamita",
    french: "Vietnamien",
    spanish: "Vietnamita",
    german: "Vietnamesisch",
    japanese: "ベトナム語",
    chinese: "越南语",
    korean: "베트남어",
    arabic: "الفيتنامية",
    indonesian: "Vietnam",
    vietnamese: "Tiếng Việt",
    netherlands: "Vietnamees",
    bhojpuri: "वियतनामी",
    nepali: "भियतनामी",
  },
  netherlands: {
    english: "Dutch",
    hindi: "डच",
    gujarati: "ડચ",
    bengali: "ডাচ",
    tamil: "டச்சு",
    telugu: "డచ్",
    kannada: "ಡಚ್",
    malayalam: "ഡച്ച്",
    kashmiri: "ڈَچ",
    urdu: "ڈچ",
    espanol: "Neerlandés",
    portuguese: "Holandês",
    italian: "Olandese",
    french: "Néerlandais",
    spanish: "Neerlandés",
    german: "Niederländisch",
    japanese: "オランダ語",
    chinese: "荷兰语",
    korean: "네덜란드어",
    arabic: "الهولندية",
    indonesian: "Belanda",
    vietnamese: "Tiếng Hà Lan",
    netherlands: "Nederlands",
    bhojpuri: "डच",
    nepali: "डच",
  },
  bhojpuri: {
    english: "Bhojpuri",
    hindi: "भोजपुरी",
    gujarati: "ભોજપુરી",
    bengali: "ভোজপুরী",
    tamil: "போஜ்புரி",
    telugu: "భోజ్పురి",
    kannada: "ಭೋಜ್ಪುರಿ",
    malayalam: "ഭോജ്പുരി",
    kashmiri: "بۄجپوری",
    urdu: "بھوجپوری",
    espanol: "Bhojpuri",
    portuguese: "Bhojpuri",
    italian: "Bhojpuri",
    french: "Bhojpuri",
    spanish: "Bhojpuri",
    german: "Bhojpuri",
    japanese: "ボージュプリー語",
    chinese: "博杰普尔语",
    korean: "보지푸리어",
    arabic: "البوجبورية",
    indonesian: "Bhojpuri",
    vietnamese: "Tiếng Bhojpuri",
    netherlands: "Bhojpuri",
    bhojpuri: "भोजपुरी",
    nepali: "भोजपुरी",
  },
  nepali: {
    english: "Nepali",
    hindi: "नेपाली",
    gujarati: "નેપાળી",
    bengali: "নেপালি",
    tamil: "நேபாளி",
    telugu: "నేపాళి",
    kannada: "ನೇಪಾಳಿ",
    malayalam: "നേപ്പാളി",
    kashmiri: "نِیپالیٖ",
    urdu: "نیپالی",
    espanol: "Nepalí",
    portuguese: "Nepalês",
    italian: "Nepalese",
    french: "Népalais",
    spanish: "Nepalí",
    german: "Nepalesisch",
    japanese: "ネパール語",
    chinese: "尼泊尔语",
    korean: "네팔어",
    arabic: "النيبالية",
    indonesian: "Nepali",
    vietnamese: "Tiếng Nepal",
    netherlands: "Nepalees",
    bhojpuri: "नेपाली",
    nepali: "नेपाली",
  },
};
